### ISSUE TITLE
How do you learn?

### ISSUE THREAD

**Issue by ilyhryh** [fabiospampinato/ama#1]
Hi Fabio!

Tell us please about your techniques

**Comment by fabiospampinato** [comment]
Very good question!

In a bit of a tongue in cheek note if I really knew the answer to that question we would be much closer to developing AI.

On a more serious note I think there are mainly 2 ways to describe the way I learn:

- I'm a visual learner: I learn quicker and better if I can see some kind of graphics representing what I'm trying to learn. I usually prefer to see some kind of animation or image rather than going through multiple pages of detailed textual explanations. Just to give a quick example in University they explained to me what the Fourier transform was, but I didn't really have any understanding of what was going on: so we are basically transforming a curve into a bunch of points, but what does this actually mean? Then I watched [this](https://en.wikipedia.org/wiki/Fourier_transform#/media/File:Fourier_transform_time_and_frequency_domains_(small).gif) wonderful GIF about it on Wikipedia and I understood what was going on on an intuitive level.

- I like making things: I like to learn things I can use, and I like to use the things I learn as soon as I learn them. For this reason I started programming kind of by going straight to the code, trying to make small changes here and there in some software other people made. I wouldn't recommend this approach for learning programming though, you'll learn much quicker if you knew some actual theory before starting to code. Nowadays if I have to learn some new library or API I go straight to the documentation first, and then as soon as I think I know enough about it I start using it.

I hope that answered the question 😄
